### PR TITLE
Modular load

### PR DESCRIPTION
**Pull request by cyvu**
Put everything inside a module instead of changing the whole workplace;

ie. a todo list should reside within a folder named todo, which is placed in the following path:
/src/template/module/todo

In this module we place all relevant the files, such as: css/todo.css, js/todo.js and todo.htm

This gives a good overview on the project as a whole, and on each modules as well.

The modules are then handled by /src/index.js which places the modules content where they belong.

At of the time of writing this pull request you manually have to provide the paths in /src/index.js, but this will change at a later date and the idea is to automatically handle the module and its content. You should just have to work with the module itself.

### CODE REVIEW

**Comment by cyvu** [comment]
What is left to do is to automatically read the content of a module and load those in without manually providing context

**Comment by cyvu** [comment]
Might want to go with the following structure: 
<br>

(root)
> src
>> module
>>> base
>>>
>>> component
>>>> example
>>>> - example.htm
>>>>
>>>>> css
>>>>>> - example.css
>>>>>
>>>>> js
>>>>>> - example.js
>>>>>
>>>>> img
>>>>>> - (images)

**Comment by cyvu** [comment]
Structure above is now in place

**Comment by cyvu** [comment]
Use node to generate a static site. The reason behind this is to access the file structure in an easy way

**Comment by cyvu** [comment]
Postponing the last request
Future additions to the base should use this structure

**Review by cyvu — COMMENTED** [review]
lgtm

**Review by Xokketeer — APPROVED** [review]
I didnt look over anything, approved.

**Pull request merged**
